use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Load .env from crate root so JUHE_API_KEY / GITEE_TOKEN are available.
    let _ = dotenvy::dotenv();

    let out = PathBuf::from(env::var("OUT_DIR").unwrap());

    let juhe_key = env::var("JUHE_API_KEY").unwrap_or_default();
    let gitee_token = env::var("GITEE_TOKEN").unwrap_or_default();

    let content = format!(
        "// Auto-generated by build.rs — do not edit.\n\
         pub const JUHE_API_KEY: &str = {juhe:?};\n\
         pub const GITEE_TOKEN: &str = {gitee:?};\n",
        juhe = juhe_key,
        gitee = gitee_token,
    );

    fs::write(out.join("generated.rs"), content).unwrap();
}
